# Uncomment the next line to define a global platform for your project
platform :ios, '15.0'

target 'DropboxBrowser' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'SwiftGen', '~> 6.0'
  pod 'SwiftLint'

  target 'DropboxBrowserTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DropboxBrowserUITests' do
    # Pods for testing
  end

end
